site_name: 'Macron API Documentation'
site_description: 'Official documentation of the Macron framework'
site_author: 'Macron'
site_url: 'https://macron.netlify.com/'

# Repository
repo_name: 'bukharim96/macron'
repo_url: 'https://github.com/bukharim96/macron'

copyright: 'Copyright &copy; 2018 Macron'

theme:
  name: 'material'
  feature:
    tabs: true
  logo:
    icon: 'book'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/bukharim96/macron'
    - type: 'twitter'
      link: 'https://twitter.com/macronjs'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: true
